const harmfulIngredients = [
  "high fructose corn syrup",
  "hfcs",
  "corn syrup",
  "glucose syrup",
  "fructose syrup",
  "glucose-fructose syrup",
  "fructose-glucose syrup",
  "invert sugar syrup",
  "aspartame",
  "e951",
  "sodium nitrite",
  "sodium nitrate",
  "potassium nitrite",
  "potassium nitrate",
  "e249",
  "e250",
  "e251",
  "e252",
  "potassium bromate",
  "e924",
  "brominated vegetable oil",
  "bvo",
  "partially hydrogenated oil",
  "partially hydrogenated vegetable oil",
  "hydrogenated oil",
  "trans fat",
  "butylated hydroxyanisole",
  "bha",
  "e320",
  "butylated hydroxytoluene",
  "bht",
  "e321",
  "azodicarbonamide",
  "ada",
  "e927",
  "red 3",
  "red dye 3",
  "erythrosine",
  "e127",
] as const;

export default harmfulIngredients;
