/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/.wrangler/tmp/bundle-2HMM14/middleware-loader.entry`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/.wrangler/tmp/bundle-A62HZP/middleware-loader.entry`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/.wrangler/tmp/bundle-UQefIJ/middleware-loader.entry`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/ai-chat`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../backend/.wrangler/tmp/bundle-2HMM14/middleware-loader.entry`; params?: Router.UnknownOutputParams; } | { pathname: `/../backend/.wrangler/tmp/bundle-A62HZP/middleware-loader.entry`; params?: Router.UnknownOutputParams; } | { pathname: `/../backend/.wrangler/tmp/bundle-UQefIJ/middleware-loader.entry`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/ai-chat`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/forgotPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../backend/.wrangler/tmp/bundle-2HMM14/middleware-loader.entry${`?${string}` | `#${string}` | ''}` | `/../backend/.wrangler/tmp/bundle-A62HZP/middleware-loader.entry${`?${string}` | `#${string}` | ''}` | `/../backend/.wrangler/tmp/bundle-UQefIJ/middleware-loader.entry${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/ai-chat${`?${string}` | `#${string}` | ''}` | `/auth/forgotPassword${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/.wrangler/tmp/bundle-2HMM14/middleware-loader.entry`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/.wrangler/tmp/bundle-A62HZP/middleware-loader.entry`; params?: Router.UnknownInputParams; } | { pathname: `/../backend/.wrangler/tmp/bundle-UQefIJ/middleware-loader.entry`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/ai-chat`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; };
    }
  }
}
